"use strict";
exports.__esModule = true;
var message = "hello world";
console.log(message);
var x = 23;
console.log(x);
var name = "resh";
console.log(name);
var reshma = "hey you ".concat(name, " how are you");
console.log(reshma);
//arithmatic operation 
var num1 = 2;
var num2 = 3;
var add = 0;
add = num1 + num2;
console.log(add);
var num3 = 2;
var num4 = 3;
var sub = 0;
sub = num3 - num4;
console.log(sub);
var num5 = 2;
var num6 = 3;
var mul = 0;
mul = num3 * num4;
console.log(mul);
console.log(typeof (reshma));
console.log(typeof (num1));
console.log(typeof (num2));
